[tool.black]                                                                    
line-length = 80                                                                
target-version = ['py38']                                                       
exclude = '''                                                                   
/(                                                                              
    \.toml                                                                      
    |\.sh                                                                       
    |\.git                                                                      
    |\.ini                                                                      
    |\.env                                                                      
    |\.ipynb                                                                    
    |azureml-models                                                             
    |notebooks                                                                  
    |Dockerfile                                                                 
    |Jenkinfile                                                                 
)/                                                                              
'''  
